import React from "react";
import Subtitle from "./Subtitle"; // Adjust the path as needed
import "./privacy.css";
import { WithTransLate } from "../../translating/index";

const PrivacyPolicy = () => {
  return (
    <div className="privacy-policy">
      <div className="sections">
        <h1>
          <WithTransLate text="IMPRINT & PRIVACY POLICY" />
        </h1>
        <p>
          <WithTransLate text="Last updated: June 2022" />
        </p>
        <p>
          <WithTransLate text="This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You." />
        </p>
        <p>
          <WithTransLate text="We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy." />
        </p>
      </div>
      {/* I. Interpretation and Definitions */}
      <>
        <Subtitle
          heading="I. Interpretation and Definitions"
          subHeading="Interpretation"
          semiSubHeading=""
          text="The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."
        />
        <Subtitle
          heading=""
          subHeading="Definitions"
          semiSubHeading=""
          text="For the purposes of this Privacy Policy:"
        />
        <ul>
          <li>
            <strong>
              <WithTransLate text="Account" />
            </strong>{" "}
            <WithTransLate text=" means a unique account created for You to access our Service or parts of our Service." />
          </li>
          <li>
            <strong>
              <WithTransLate text="Company" />
            </strong>{" "}
            <WithTransLate
              text={` (referred to as either "the Company","We", "Us" or "Our" in this Agreement) refers to `}
            />
            <strong>
              <WithTransLate text="Blue House B&B" />
            </strong>
            <WithTransLate text=", Valhusabraut 19, Seltjarnarnes, 170, Iceland and " />
            <strong>
              <WithTransLate text="Grotta Northern Lights apartment" />
            </strong>
            <WithTransLate text=", Valhusabraut 35, Seltjarnarnes, 170, Iceland." />
          </li>
          <li>
            <strong>
              <WithTransLate text="Cookies" />
            </strong>{" "}
            <WithTransLate text="are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." />
          </li>
          <li>
            <strong>
              <WithTransLate text="Country" />
            </strong>{" "}
            <WithTransLate text="refers to: Iceland" />
          </li>
          <li>
            <strong>
              <WithTransLate text="Device" />
            </strong>{" "}
            <WithTransLate text="means any device that can access the Service such as a computer, a cell phone or a digital tablet." />
          </li>
          <li>
            <strong>
              <WithTransLate text="Personal Data" />
            </strong>{" "}
            <WithTransLate text="is any information that relates to an identified or identifiable individual." />
          </li>
          <li>
            <strong>
              <WithTransLate text="Service" />
            </strong>{" "}
            <WithTransLate text="refers to the Website." />
          </li>
          <li>
            <strong>
              <WithTransLate text="Service Provider" />
            </strong>{" "}
            <WithTransLate text="means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." />
          </li>
          <li>
            <strong>
              <WithTransLate text="Usage Data" />
            </strong>{" "}
            <WithTransLate text="refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." />
          </li>
          <li>
            <strong>
              <WithTransLate text="Website" />
            </strong>{" "}
            <WithTransLate text="refers to Blue House B&B, accessible from " />
            <a href="https://bluehouse.is/">
              <WithTransLate text="https://bluehouse.is/" />
            </a>{" "}
            <WithTransLate text="and Grotta Northern Lights apartment, accessible from " />
            <a href="https://grottanorthernlights.com/">
              <WithTransLate text="https://grottanorthernlights.com/" />
            </a>
          </li>
          <li>
            <strong>
              <WithTransLate text="You" />
            </strong>{" "}
            <WithTransLate text="means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." />
          </li>
        </ul>
      </>
      {/* II. Collecting and Using Your Personal Data */}
      <>
        {" "}
        <Subtitle
          heading="II. Collecting and Using Your Personal Data"
          subHeading="A. Types of Data Collected"
          semiSubHeading="1. Personal Data"
          text="While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:"
        />
        <ul>
          <li>
            <WithTransLate text="First name and last name" />
          </li>
          <li>
            <WithTransLate text="Email address" />
          </li>
          <li>
            <WithTransLate text="Phone number" />
          </li>
          <li>
            <WithTransLate text="Address, State, Province, ZIP/Postal code, City" />
          </li>
          <li>
            <WithTransLate
              text="Phone number
"
            />
          </li>
          <li>
            <WithTransLate
              text="Credit card details
"
            />
          </li>
        </ul>
        <Subtitle
          heading=""
          subHeading=""
          semiSubHeading="2. Usage Data"
          text="Usage Data is collected automatically when using the Service."
        />
        <p>
          <WithTransLate
            text="Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
"
          />
        </p>
        <p>
          <WithTransLate
            text="When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
"
          />
        </p>
        <p>
          <WithTransLate
            text="We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
"
          />
        </p>
        <Subtitle
          heading=""
          subHeading=""
          semiSubHeading="3. Comments"
          text="When You leave comments on the site We collect the data shown in the comments form, and also Your IP address and browser agent string to help spam detection.
"
        />
        <p>
          <WithTransLate
            text="An anonymized string created from Your email address (also called a hash) may be provided to the Gravatar service to see if You are 
          "
          />
        </p>
        <Subtitle
          heading=""
          subHeading=""
          text={`using the service. The Gravatar service privacy policy is available here: <a href=" https://automattic.com/privacy/."> https://automattic.com/privacy/.</a>
             After approval of Your comment, Your profile picture is visible to the public in the context of Your comment.`}
        />
        <Subtitle
          heading=""
          subHeading=""
          semiSubHeading="4. Media"
          text="If You upload images to the website, You should avoid uploading images with embedded location data (EXIF GPS) included. Any visitors to the website can download and extract any location data from images on the website.

"
        />
        <Subtitle
          heading=""
          subHeading=""
          semiSubHeading="5. Cookies"
          text="We use Cookies to track the activity on Our Service and store certain information."
        />
        <p>
          <WithTransLate text="We use both Session and Persistent Cookies for the purposes set out below:" />
        </p>
        <ul>
          <li>
            <strong>
              <WithTransLate
                text="Necessary / Essential Cookies
"
              />
            </strong>{" "}
            <p>
              <WithTransLate
                text={
                  "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."
                }
              />
            </p>
          </li>
          <li>
            <strong>
              <WithTransLate
                text="
Cookies Policy / Notice Acceptance Cookies

"
              />
            </strong>{" "}
            <p>
              <WithTransLate
                text={
                  "These Cookies identify if users have accepted the use of cookies on the Website."
                }
              />
            </p>
          </li>
          <li>
            <strong>
              <WithTransLate text="Functionality Cookies" />
            </strong>{" "}
            <p>
              <WithTransLate
                text={
                  "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website. For example:"
                }
              />
            </p>
            <p>
              <WithTransLate
                text={
                  "1. If You leave a comment on Our Site You may opt-in to saving Your name, email address and website in cookies. These are for Your convenience so that You do not have to fill in your details again when You leave another comment. These cookies will last for one year."
                }
              />
            </p>
            <p>
              <WithTransLate
                text={
                  "2. When You log in, we will also set up several cookies to save Your login information and Your screen display choices. Login cookies last for two days, and screen options cookies last for a year. If You select “Remember Me”, Your login will persist for two weeks. If You log out of Your account, the login cookies will be removed."
                }
              />
            </p>
            <p>
              <WithTransLate
                text={
                  "3. If You edit or publish an article, an additional cookie will be saved in Your browser. This cookie includes no personal data and simply indicates the post ID of the article You just edited. It expires after 1 day."
                }
              />
            </p>
          </li>
        </ul>
      </>
      {/* B. Use of Your Personal Data */}
      <>
        <Subtitle
          heading=""
          subHeading="B. Use of Your Personal Data"
          semiSubHeading=""
          text="The Company may use Personal Data for the following purposes:"
        />
        <ul>
          <li>
            <p>
              {" "}
              <WithTransLate
                text="To provide and maintain our Service, including to monitor the usage of our Service.
"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.

"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.

"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="To manage Your requests: To attend and manage Your requests to Us

"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.


"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.



"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="We may share Your personal information in the following situations:




"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.




"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.





"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.





"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.






"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="With Your consent: We may disclose Your personal information for any other purpose with Your consent.






"
              />
            </p>
          </li>
        </ul>
      </>
      {/* C. Retention of Your Personal Data */}
      <>
        <Subtitle
          heading=""
          subHeading="C. Retention of Your Personal Data"
          semiSubHeading=""
          text="The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
"
        />
        <p>
          <WithTransLate
            text="The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
"
          />
        </p>
        <p>
          <WithTransLate
            text="For users that register on our website (if any), We also store the personal information they provide in their user profile. All users can see, edit, or delete their personal information at any time (except they cannot change their username). Website administrators can also see and edit that information.
"
          />
        </p>
      </>
      {/* D. Disclosure of Your Personal Data */}
      <>
        <Subtitle
          heading=""
          subHeading="D. Disclosure of Your Personal Data"
          semiSubHeading="1. Law enforcement"
          text="Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
"
        />
        <Subtitle
          heading=""
          semiSubHeading="2. Other legal requirements
"
          text="The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:

"
        />
        <ul>
          <li>
            <p>
              <WithTransLate text="Comply with a legal obligation" />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Protect and defend the rights or property of the Company
"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Prevent or investigate possible wrongdoing in connection with the Service
"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate text="Protect the personal safety of Users of the Service or the public" />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Protect against legal liability
"
              />
            </p>
          </li>
        </ul>
      </>
      {/* E. Security of Your Personal Data */}
      <>
        <Subtitle
          heading=""
          subHeading="E. Security of Your Personal Data"
          semiSubHeading=""
          text="The security of Your Personal Data is important to Us but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
"
        />
      </>
      {/* F. Embedded content from other websites */}
      <>
        <Subtitle
          heading=""
          subHeading="F. Embedded content from other websites"
          semiSubHeading=""
          text="Articles on Our site may include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website."
        />
        <p>
          <WithTransLate
            text={
              "These websites may collect data about You, use cookies, embed additional third-party tracking, and monitor Your interaction with that embedded content, including tracking Your interaction with the embedded content if You have an account and are logged in to that website."
            }
          />
        </p>
      </>
      {/* III. What rights do you have over your data?
       */}
      <>
        <Subtitle
          heading="III. What rights do you have over your data?
"
          subHeading=""
          text="If you have an account on this site, or have left comments, you can request to receive an exported file of the personal data we hold about you, including any data you have provided to us. You can also request that we erase any personal data we hold about you. This does not include any data we are obliged to keep for administrative, legal, or security purposes.

"
        />

        <p>
          <WithTransLate
            text={
              "You have several rights under data-protection law in relation to how we use your personal information. You have the right, free of charge, to:"
            }
          />
        </p>

        <ul>
          <li>
            <p>
              <WithTransLate
                text="	Request a copy of the personal information we hold about you in a structured, commonly used and machine readable format;
"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Rectify any inaccurate personal information we hold about you;

"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Withdraw your consent where we have relied upon your consent to process your information;

"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Erase the personal information we hold about you subject to certain exceptions;
"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Restrict processing of your personal information in certain circumstances;

"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Object to our use of your personal information for our legitimate interests, for profiling and for direct marketing purposes;


"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Not be subject to a decision which is based solely on automated processing where that decision produces a legal effect on you or otherwise significantly affects you. We do not make automated decisions of this nature;



"
              />
            </p>
          </li>
          <li>
            <p>
              <WithTransLate
                text="Lodge a complaint with the appropriate data-protection authority if you have concerns about how we process your personal data.



"
              />
            </p>
          </li>
        </ul>
        <p>
          <WithTransLate text="Where we need to collect personal data by law, or under the terms of a contract we have with you and you fail to provide that data when requested, we may not be able to perform the contract we have or are trying to enter into with you (for example, to provide you with goods or services). In this case, we may have to cancel a product or service you have with us but we will notify you if this is the case at the time." />
        </p>
      </>
      {/* IV. Changes to this Privacy Policy */}
      <>
        <Subtitle
          heading="IV. Changes to this Privacy Policy"
          subHeading=""
          semiSubHeading=""
          text="We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
"
        />
        <p>
          <WithTransLate
            text={`We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
`}
          />
        </p>
        <p>
          <WithTransLate
            text={`You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

`}
          />
        </p>
      </>
      {/* V. Contact Us */}
      <>
        <Subtitle
          heading="V. Contact Us"
          subHeading=""
          semiSubHeading=""
          text="If you have any questions about this Privacy Policy, You can contact us:"
        />
        <ul>
          <li>
            <WithTransLate text="By email: " />
            <a href="mailto:info@bluehouse.is">info@bluehouse.is</a> or{" "}
            <a href="mailto:info@grottanorthernlights.com">
              info@grottanorthernlights.com
            </a>
          </li>
          <li>
            <WithTransLate text="By visiting this page on our website: " />
            <a href="https://bluehouse.is/privacy-and-policy">
              https://bluehouse.is/privacy-and-policy
            </a>
          </li>

          <li>
            <WithTransLate text="By phone number: +354 775 6480" />
          </li>
        </ul>
      </>

      {/* cookie policy */}

      <>
        <h1>
          <WithTransLate text="COOKIE POLICY" />
        </h1>
        <Subtitle
          heading=""
          subHeading=""
          semiSubHeading=""
          text={`In order to provide you with a more personalized and responsive service we need to remember and store information about how you use this website. This is done using small text files called cookies. Cookies contain small amounts of information and are downloaded to your computer or other device by a server for this website. Your web browser then sends these cookies back to this Website on each subsequent visit so that it can recognize you and remember things like your user preferences. A cookie is a small file of letters and numbers that we store on your browser and hard drive of your computer. Cookies contain information that is transferred to your computer’s hard drive. By browsing our sites you are accepting our use of cookies. You can close the cookie notification by clicking “OK” button.
`}
        />

        <ul>
          <li>
            <strong>
              <WithTransLate text="Necessary cookies" />
            </strong>{" "}
            <WithTransLate
              text="These are cookies that are required for the operation of our website. They include cookies that enable you to log into secure areas of our website as well as placing products in your cart.
"
            />
          </li>
          <li>
            <strong>
              <WithTransLate text="Preference settings cookies" />
            </strong>{" "}
            <WithTransLate
              text={` These are cookies that are required for the operation of some features our website. They include cookies that enable changes of some settings on our websites.
`}
            />
          </li>
          <li>
            <strong>
              <WithTransLate text="Statistics, analytical and performance cookies" />
            </strong>{" "}
            <WithTransLate
              text="They allow us to recognize and count the number of visitors and to see how visitors move around our website when they are using it.
"
            />
          </li>
          <li>
            <strong>
              <WithTransLate
                text=" Marketing cookies 
"
              />
            </strong>{" "}
            <WithTransLate
              text="These cookies can be connected to your social accounts to display advertisements to your social accounts.
"
            />
          </li>

          <p>
            <WithTransLate
              text={`Most browsers will allow you to see what cookies you have and delete them on an individual basis or block cookies from particular or all websites. Be aware that any preference you have set will be lost if you delete all cookies, including your preference to close the cookie notification.`}
            />
          </p>
        </ul>
        <Subtitle
          heading=""
          subHeading="Our cookies and 3rd party cookies used on our sites"
          semiSubHeading=""
          text=""
        />
      </>

      <div className="cookies-table">
        <div className="section">
          <h2>
            <WithTransLate text="Advertisement" />
          </h2>
          <ul>
            <li>
              <WithTransLate text="TAUnique" />{" "}
              <span>
                <a href="https://tripadvisor.com">
                  <WithTransLate text=".tripadvisor.com" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="TACds" />{" "}
              <span>
                <a href="https://tripadvisor.com">
                  <WithTransLate text=".tripadvisor.com" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="b3e783bb62" />{" "}
              <span>
                <a href="https://salesiq.zoho.eu">
                  <WithTransLate text="salesiq.zoho.eu" />
                </a>
              </span>
            </li>
          </ul>
        </div>

        <div className="section">
          <h2>
            <WithTransLate text="Analytics" />
          </h2>
          <ul>
            <li>
              <WithTransLate text="_ga" />{" "}
              <span>
                <a href="https://bluehouse.is">
                  <WithTransLate text=".bluehouse.is" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="_gid" />{" "}
              <span>
                <a href="https://bluehouse.is">
                  <WithTransLate text=".bluehouse.is" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="_gat_UA-923879896-1" />{" "}
              <span>
                <a href="https://bluehouse.is">
                  <WithTransLate text=".bluehouse.is" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="_ga_6QGX4YP9SF" />{" "}
              <span>
                <a href="https://bluehouse.is">
                  <WithTransLate text=".bluehouse.is" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="LaVisitorNew" />{" "}
              <span>
                <a href="https://bluehouse.is">
                  <WithTransLate text=".bluehouse.is" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="LaSID" />{" "}
              <span>
                <a href="https://bluehouse.is">
                  <WithTransLate text=".bluehouse.is" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="_ga_WYRZ6Q7MDE" />{" "}
              <span>
                <a href="https://bluehouse.is">
                  <WithTransLate text=".bluehouse.is" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="TADCID" />{" "}
              <span>
                <a href="https://www.tripadvisor.com">
                  <WithTransLate text="www.tripadvisor.com" />
                </a>
              </span>
            </li>
          </ul>
        </div>

        <div className="section">
          <h2>
            <WithTransLate text="Functional" />
          </h2>
          <ul>
            <li>
              <WithTransLate text="TASession" />{" "}
              <span>
                <a href="https://tripadvisor.com">
                  <WithTransLate text=".tripadvisor.com" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="ServerPool" />{" "}
              <span>
                <a href="https://tripadvisor.com">
                  <WithTransLate text=".tripadvisor.com" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="_zcsr_tmp" />{" "}
              <span>
                <a href="https://salesiq.zoho.eu">
                  <WithTransLate text="salesiq.zoho.eu" />
                </a>
              </span>
            </li>
          </ul>
        </div>

        <div className="section">
          <h2>
            <WithTransLate text="Necessary" />
          </h2>
          <ul>
            <li>
              <WithTransLate text="LS_CSRF_TOKEN" />{" "}
              <span>
                <a href="https://salesiq.zoho.eu">
                  <WithTransLate text="salesiq.zoho.eu" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="zfccn" />{" "}
              <span>
                <a href="https://pagesense-collect.zoho.eu">
                  <WithTransLate text="pagesense-collect.zoho.eu" />
                </a>
              </span>
            </li>
            <li>
              <WithTransLate text="JSESSIONID" />{" "}
              <span>
                <a href="https://maillist-manage.eu">
                  <WithTransLate text="maillist-manage.eu" />
                </a>
              </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
